name: Publish wiki
on:
  push:
    branches: [wiki]
    paths:
      - docs/**
      - .github/workflows/sync-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: impresscms-dev/strip-markdown-extensions-from-links-action@v2.0.1
        with:
          path: docs
      - uses: newrelic/wiki-sync-action@main
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}